.TH AT 1
.SH NAME
at - Execute a command from within a specified directory.

.SH SYNOPSIS
\fBat \fI<directory> <command>\fR

.SH DESCRIPTION
\fBat\fP is a tool for executing a command from within a certain directory.

.SH EXAMPLES
    at ~/.config git init

.SH TIPS
To get the most out of these utilities, it is best to change your bash aliases to functions. Aliases are deprecated.

Replace this line in your ~/.bashrc:
    
    alias ls='ls --color=auto'

With this:
    
    ls() {
        ls --color=auto "$@"
    }
    export -f ls

Then your aliases will work with subscripts like inall and at.

.SH AUTHOR
Dan Persons (dpersonsdev@gmail.com)

.SH COPYRIGHT
MIT License

Copyright (c) 2017 Dan Persons

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
