.TH SUSH 1
.SH NAME
sush - Execute a multi-line command with sudo privilages.

.SH SYNOPSIS
\fBsush \fP[\fB-hv\fP] \fI'<commands>'\fR

.SH OPTIONS

    \fB-h\fP                  Print the help message
    \fB-v\fP                  Print the version number

.SH DESCRIPTION
\fBsush\fP is a tool for executing multiple commands with sudo privileges.

.SH EXAMPLES
    sush 'apt update;apt upgrade'
    sush 'whoami;uid'

.SH FILES
    {/usr/local|~/.local}/share/doc/dirutils/README.md
    {/usr/local|~/.local}/share/doc/dirutils/CHANGELOG.md
    {/usr/local|~/.local}/share/doc/dirutils/LICENSE

.SH AUTHOR
Dan Persons (dpersonsdev@gmail.com)

.SH COPYRIGHT
MIT License

Copyright (c) 2017 Dan Persons

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
